name: bekmar_dbt
version: '1.0'
config-version: 2
profile: bekmar_dbt

model-paths: ["models"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
docs-paths: ["docs"]
asset-paths: ["assets"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
quoting:
  database: false
  schema: false
  identifier: true
tests:
  bekmar_dbt:
    +severity: error
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['bekmar_dbt', 'dbt_utils']
vars:
  cal_start_date: '2010-01-01'
  cal_end_date: '2030-12-31'

models:
  bekmar_dbt:
    raw:
      +schema: raw
      +materialized: view
    staging:
      +schema: stg
      +materialized: view
    dwh:
      +schema: dwh
      +materialized: table
    report:
      +schema: report
      +materialized: view
    dim_date:
      +materialized: table

seeds:
  bekmar_dbt:  # Replace with your actual dbt project name
    locations:
      file: seed/locations.csv